config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get "about" => 'static_pages#about'

  get "contact" => 'static_pages#contact'

  get "projects" => 'static_pages#projects'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def projects
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Steve Aragon's Webpage"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="#">Steve Aragon Webpage</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Steve Aragon's Webpage", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "About",   about_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "Projects", projects_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
</body>
</html>

app/views/static_pages/about.html.erb
<%= provide(:title, "About") %>
<h1>About me</h1>
<p>Description of me</p>

app/views/static_pages/contact.html.erb
<%= provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  <ul>
    <li><a href="mailto:me@stevearagon.io">me (at) stevearagon.io</a></li>
    <li><a href="http://www.instagram.com/newsteve">instagram: newsteve</a></li>
    <li><a href="http://www.twitter.com/the_new_steve">twitter: the_new_steve</a></li>
    <li><a href="http://www.github.com/stearagon">github: stearagon</a></li>
  </ul>
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Steve Aragon's Webpage</h1>

  <h2>
    This is the home page to learn about me, my projects and my contact info.
  </h2>
</div>

app/views/static_pages/projects.html.erb
<%= provide(:title, "Projects") %>
<h1>Projects</h1>
<p>
  Here is a list of projects I am working on:
  <ul>
    <li>sample</li>
  </ul>
</p>